name: pop_starter_kit
description: An introduction to raw feeding your pet.
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  auto_route: 7.7.0
  flutter_hooks: 0.18.6
  freezed_annotation: 2.2.0
  http: 1.1.0
  shared_preferences: 2.2.0
  get_it: 7.6.0
  flutter_html: 3.0.0-beta.2
  js: 0.6.7
  google_fonts: 5.1.0
  youtube_player_iframe: 4.0.4
  awesome_dialog: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator:
  build_runner:
  freezed:

flutter:
  uses-material-design: true
