name: pop_starter_kit
description: An introduction to raw feeding your pet.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  auto_route: 7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator:
  build_runner:
  flutter_lints: 2.0.0

flutter:
  uses-material-design: true
